### ISSUE TITLE
No pages displayed

### ISSUE THREAD

**Issue by guidoferreyra** [jongacnik/kirby-index-field#11]
I installed the plugin and added the following in the snippet, but nothing is displayed.
Any ideas? Thanks in advance.

```
  pageindex:
    label: Items
    type: index
    options: children
```

Here a screenshot how it looks in the panel.
![captura de pantalla 2017-11-09 a las 2 12 38 p m](https://user-images.githubusercontent.com/1755590/32619076-5f1bc5c2-c558-11e7-8116-0eee3ba8e75b.png)
