### ISSUE TITLE
How can I format the modified date field?

### ISSUE THREAD

**Issue by foopz** [jongacnik/kirby-index-field#17]
Such a useful plugin, thank you much. I'm trying to [filter](https://github.com/jongacnik/kirby-index-field#filter-data) the modified date and format it as 'd/m/Y', but I'm a PHP novice and am struggling to get to grips with how it works. Any pointers would be greatly appreciated. Below is my code based on the response to [#16](https://github.com/jongacnik/kirby-index-field/issues/16).
```
class IndexDataFilter {
    static function indexDataFunction($data) {
        foreach ($data as $item) {
            $p = page($item['uri']);
            $date = $p->modified()->date('d/m/Y');
            $item['modified'] = $date;
        }
        return $data;
    }
} 
```

```
  projects:
    label: Projects
    type:  index
    options: children
    filter: IndexDataFilter::indexDataFunction
    columns:
      num: Number
      title: Title
      tags: Tags
      modified: Date Modified
    query:
      template: project
    rows: 25
```
