### ISSUE TITLE
Feature: More Sorting Abilities

### ISSUE THREAD

**Issue by wottpal** [jongacnik/kirby-index-field#8]
The ability to define a custom column for the initial sort-order would be great. Or going one step further and allow to define the sort-order just like Kirby does with subpages. (Also with multiple fields).

```yaml
# Example
…
pages:
  sort: year asc title desc
…
```

When I am back I I'll just browse a little bit through Kirbys core because there already has to be a function which parses & does exactly this. Would you appreciate an addition like this to the core?  

Dennis
